version: "3"
services:
  backend:
    # build: 
    #   dockerfile: Dockerfile
    #   context: ./
    image: conradmaker/typescript-docker
    container_name: app_backend
    # ports:
    #   - "5000:8080"
    environment:
      PORT: 8080
  nginx: 
    restart: always
    image: conradmaker/typescript-nginx
    ports: 
      - "80:80"