version: "3"
services:
  server:
    # container_name: app_server4
    # build: 
    #   dockerfile: Dockerfile
    #   context: ./
    image: conradmaker/typescript-docker
    # volumes:
      # - /usr/app/node_modules
      # - /app/build
      # - ./:/usr/app/
    ports:
      - "5000:8080"
    environment:
      PORT: 8080